test,conformance-ingress: Change sanity check to deal with ICMP reply
The current ingress conformance test adds an ingress and then does a
curl to confirm it works. In the past, Cilium would have dropped the
request packet until the datapath was setup. This silent dropping causes
curl to retry for 15 seconds before giving up.

With the ICMP reply however, curl gets an immediate response and will
give up immediately. This causes the test to fail. So this commit
adds manual retry logic and delays in the test script.

Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>

diff --git a/.github/workflows/conformance-ingress.yaml b/.github/workflows/conformance-ingress.yaml
--- a/.github/workflows/conformance-ingress.yaml
+++ b/.github/workflows/conformance-ingress.yaml
@@ -243,7 +243,21 @@ jobs:
         timeout-minutes: 5
         run: |
           lb=$(kubectl get ingress basic-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-          curl -s -v --connect-timeout 5 --max-time 20 --retry 3 --fail -- http://"$lb"
+          
+          # It may take some time after the service gets created for it to handle traffic.
+          # An un-ready service will return an ICMP so we retry a few times since the --retry
+          # flag only retries on connection timeouts.
+          set +e
+          for i in $(seq 1 3); do
+              curl -s -v --connect-timeout 5 --max-time 20 --fail -- http://"$lb" && break
+              sleep 5
+          done
+          set -e
+          
+          # Confirm that after the service is ready, it can handle traffic
+          curl -s -v --connect-timeout 5 --max-time 20 --fail -- http://"$lb" || (echo "Failed $i"; exit -1)
+
+          # By now the service should be up, no need to do the manual retries for the second request
           curl -s -v --connect-timeout 5 --max-time 20 --retry 3 --fail -- http://"$lb"/details/1
 
       - name: Run Sanity check (internal to NodePort)
